<?php

declare(strict_types=1);

namespace Kaneas\Install;

use Kaneas\Core\Database;
use Kaneas\Core\Migrator;
use Kaneas\Services\Passwords;
use Kaneas\Services\Settings;
use PDO;

/**
 * Install logic shared by the web installer (index.php) and the CLI installer (cli.php).
 */
final class Installer
{
    public function __construct(private readonly string $appDir)
    {
    }

    public function configPath(): string
    {
        return $this->appDir . '/api/config/config.php';
    }

    public static function tablesExist(PDO $pdo, string $prefix): bool
    {
        $stmt = $pdo->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?');
        $stmt->execute([$prefix . 'users']);
        return $stmt->fetchColumn() !== false;
    }

    /**
     * @param array{
     *   db: array{host:string,port:int,name:string,user:string,pass:string,prefix:string},
     *   admin: array{name:string,email:string,password:string,locale:string},
     *   users?: list<array{name:string,email:string,password:string,role:string,locale:string}>,
     *   mail?: array,
     *   allow_registration: bool,
     *   app_url: string,
     *   base_path: string,
     *   debug?: bool,
     * } $options
     * @throws InstallException
     */
    public function install(array $options): void
    {
        $dbConfig = $options['db'];

        try {
            $pdo = Database::connect($dbConfig);
        } catch (\PDOException $e) {
            throw new InstallException('db', $e->getMessage(), $e);
        }
        if (self::tablesExist($pdo, $dbConfig['prefix'])) {
            throw new InstallException('exists', $dbConfig['prefix']);
        }
        $db = new Database($pdo, $dbConfig['prefix']);

        $statements = Migrator::statements((string) file_get_contents(__DIR__ . '/schema.sql'), prefix: $dbConfig['prefix']);
        preg_match_all('/CREATE TABLE `([^`]+)`/', implode("\n", $statements), $m);
        $createdTables = $m[1];

        $appKey = base64_encode(random_bytes(32));

        try {
            foreach ($statements as $statement) {
                $pdo->exec($statement);
            }

            Settings::set('schema_version', KANEAS_SCHEMA_VERSION, $db);
            Settings::set('installed_at', gmdate('c'), $db);
            Settings::set('allow_registration', $options['allow_registration'], $db);
            Settings::saveMail(($options['mail'] ?? []) + ['enabled' => false], $db, $appKey);

            $users = [['role' => 'admin'] + $options['admin'], ...($options['users'] ?? [])];
            foreach ($users as $user) {
                $db->query(
                    'INSERT INTO {users} (email, name, password_hash, role, locale, email_verified_at)
                     VALUES (?, ?, ?, ?, ?, UTC_TIMESTAMP())',
                    [strtolower($user['email']), $user['name'], Passwords::hash($user['password']), $user['role'], $user['locale']],
                );
            }

            $this->writeConfig([
                'db' => $dbConfig,
                'jwt' => [
                    'secret' => base64_encode(random_bytes(64)),
                    'access_ttl' => 900,
                    'refresh_ttl' => 60 * 60 * 24 * 30,
                ],
                'app' => [
                    'url' => $options['app_url'],
                    'key' => $appKey,
                    'debug' => $options['debug'] ?? false,
                ],
            ]);
        } catch (\Throwable $e) {
            // DDL auto-commits in MySQL, so roll back by dropping what we created.
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
            foreach (array_reverse($createdTables) as $table) {
                $pdo->exec('DROP TABLE IF EXISTS `' . $table . '`');
            }
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
            throw $e instanceof InstallException ? $e : new InstallException('install', $e->getMessage(), $e);
        }

        $this->configureFrontend($options['base_path']);
    }

    /** Locks the web installer folder. */
    public function lock(): void
    {
        @file_put_contents(
            __DIR__ . '/.htaccess',
            "<IfModule mod_authz_core.c>\n    Require all denied\n</IfModule>\n<IfModule !mod_authz_core.c>\n    Order deny,allow\n    Deny from all\n</IfModule>\n",
        );
    }

    private function writeConfig(array $config): void
    {
        $php = "<?php\n\n// Generated by the Kaneas installer on " . gmdate('c') . ". Keep this file private.\nreturn "
            . var_export($config, true) . ";\n";
        $tmp = $this->configPath() . '.tmp';
        if (file_put_contents($tmp, $php, LOCK_EX) === false || !rename($tmp, $this->configPath())) {
            throw new InstallException('write');
        }
        @chmod($this->configPath(), 0640);
    }

    /** Points the Angular build at the folder it is installed in (sub folder support). */
    private function configureFrontend(string $basePath): void
    {
        $index = $this->appDir . '/index.html';
        if (is_file($index) && is_writable($index)) {
            $html = (string) file_get_contents($index);
            $html = (string) preg_replace('/<base href="[^"]*"\s*\/?>/', '<base href="' . htmlspecialchars($basePath, ENT_QUOTES) . '">', $html, 1);
            file_put_contents($index, $html);
        }
        $htaccess = $this->appDir . '/.htaccess';
        if (is_file($htaccess) && is_writable($htaccess)) {
            $rules = (string) file_get_contents($htaccess);
            $rules = (string) preg_replace('/^(\s*)RewriteBase\s+\S+/m', '${1}RewriteBase ' . $basePath, $rules);
            file_put_contents($htaccess, $rules);
        }
    }
}

/** `reason` is one of: db, exists, write, install. */
final class InstallException extends \RuntimeException
{
    public function __construct(public readonly string $reason, string $message = '', ?\Throwable $previous = null)
    {
        parent::__construct($message, 0, $previous);
    }
}
